name: lmaaddition
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - aiobotocore=2.23.2
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aioitertools=0.12.0
  - aiosignal=1.2.0
  - alabaster=0.7.16
  - aom=3.6.0
  - arm_pyart=2.1.0
  - arrow=1.3.0
  - arrow-cpp=19.0.0
  - astroid=3.3.8
  - asttokens=3.0.0
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - attrs=24.3.0
  - autopep8=2.0.4
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - babel=2.16.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.4
  - binaryornot=0.4.4
  - black=25.1.0
  - bleach=6.2.0
  - blosc=1.21.6
  - bokeh=3.6.2
  - boost-cpp=1.82.0
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.8.3
  - cairo=1.16.0
  - cartopy=0.25.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cftime=1.6.4
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cloudpickle=3.1.1
  - cmweather=0.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cryptography=45.0.5
  - cycler=0.11.0
  - dask=2025.5.1
  - dask-core=2025.5.1
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - deprecation=2.1.0
  - diff-match-patch=20200713
  - dill=0.3.8
  - distributed=2025.5.1
  - docstring-to-markdown=0.11
  - docutils=0.21.2
  - executing=0.8.3
  - expat=2.7.1
  - flake8=7.1.1
  - flexcache=0.3
  - flexparser=0.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2025.7.0
  - gdal=3.11.0
  - geographiclib=2.0
  - geopy=2.4.1
  - geos=3.10.6
  - geotiff=1.7.0
  - gflags=2.2.2
  - git=2.45.2
  - glog=0.5.0
  - graphite2=1.3.14
  - h5netcdf=1.6.3
  - h5py=3.14.0
  - harfbuzz=10.2.0
  - hdf4=4.2.13
  - hdf5=1.14.5
  - heapdict=1.0.1
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - inflection=0.5.1
  - intel-openmp=2024.2.1
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - isort=6.0.1
  - jaraco.classes=3.2.1
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - jmespath=1.0.1
  - jpeg=9e
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.15
  - keyring=25.6.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lat_lon_parser=1.3.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libavif=1.1.1
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.14.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libffi=3.4.4
  - libgdal-core=3.11.0
  - libglib=2.84.2
  - libgrpc=1.71.0
  - libiconv=1.16
  - libkml=1.3.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libnetcdf=4.8.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzip=1.8.0
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mda-xdrlib=0.2.0
  - mdurl=0.1.0
  - metpy=1.7.0
  - minizip=4.0.3
  - mistune=3.1.2
  - mkl=2024.2.2
  - more-itertools=10.3.0
  - mpi=1.0
  - mpi4py=4.0.3
  - msgpack-python=1.1.1
  - msmpi=10.1.1
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - numpy=2.3.2
  - numpydoc=1.9.0
  - open-radar-data=0.5.0
  - openjpeg=2.5.2
  - openssl=3.5.1
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.3.1
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - pathspec=0.12.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pint=0.24.4
  - pip=25.1
  - pixman=0.40.0
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - ply=3.11
  - pooch=1.8.2
  - proj=9.3.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=19.0.0
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pylint=3.3.5
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pypalettes=0.1.6
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-lmdb=1.6.2
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-slugify=5.0.2
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytoolconfig=1.2.6
  - pytz=2025.2
  - pyuca=1.2
  - pywin32=308
  - pywin32-ctypes=0.2.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - re2=2024.07.02
  - referencing=0.30.2
  - requests=2.32.4
  - rich=13.9.4
  - roman-numerals-py=3.1.0
  - rope=1.13.0
  - rpds-py=0.22.3
  - rtree=1.0.1
  - s3fs=2025.7.0
  - scipy=1.16.0
  - setuptools=78.1.1
  - setuptools-scm=8.3.1
  - setuptools_scm=8.3.1
  - shapely=2.1.1
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spyder=6.0.7
  - spyder-kernels=3.0.5
  - sqlite=3.50.2
  - stack_data=0.2.0
  - superqt=0.7.3
  - tbb=2021.8.0
  - tblib=3.1.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tomlkit=0.13.2
  - toolz=1.0.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unidecode=1.3.8
  - uriparser=0.9.8
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - vc=14.3
  - vc14_runtime=14.44.35208
  - versioneer=0.29
  - vs2015_runtime=14.44.35208
  - watchdog=4.0.2
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - wradlib=2.4.0
  - wrapt=1.17.0
  - xarray=2025.7.1
  - xerces-c=3.2.4
  - xmltodict=0.14.2
  - xradar=0.10.0
  - xyzservices=2022.9.0
  - xz=5.6.4
  - yaml=0.2.5
  - yapf=0.40.2
  - yarl=1.18.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - boto3==1.40.2
      - botocore==1.40.2
      - nexradaws==1.1
      - pyxlma==0.1
      - s3transfer==0.13.1