name: LMAAddition
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - arm_pyart
  - cartopy==0.22.0
  - conda
  - spyder
  - geopy
  - pandas
  - conda-forge::arm_pyart
  - conda-forge::ipywidgets
  - conda-forge::metpy
  - conda-forge::pymap3d
  - conda-forge::pypalettes
  - conda-forge::geodatasets
  - conda-forge::geopandas
  - conda-forge::wradlib
  - conda-forge::xarray
  - jupyterlab_widgets
  - ipympl
  - jupyterlab
  - xarray
  - pip:
      - git+https://github.com/Bee-BeanBag/xlma-python.git
      - xarray
      - arm_pyart
      - git+https://github.com/Bee-BeanBag/InteractiveLMA_Addition.git
      - nexradaws











